// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Entities;

namespace Repository;

public partial class ShopContext : DbContext
{
    public ShopContext(DbContextOptions<ShopContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Category> Categories { get; set; }
    public virtual DbSet<Order> Orders { get; set; }
    public virtual DbSet<OrderItem> OrderItems { get; set; }
    public virtual DbSet<Product> Products { get; set; }
    public virtual DbSet<ProductImage> ProductImages { get; set; }
    public virtual DbSet<PropertyInquiry> PropertyInquiries { get; set; }
    public virtual DbSet<AdminInquiry> AdminInquiries { get; set; }
    public virtual DbSet<Rating> Ratings { get; set; }
    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__Categori__19093A2B32A18246");

            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");

            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.Description).HasMaxLength(500);
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__Orders__C3905BAF00034DE6");

            entity.Property(e => e.OrderId).HasColumnName("OrderID");

            entity.Property(e => e.OrderDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Pending");

            entity.Property(e => e.TotalAmount)
                .HasColumnType("decimal(18, 2)");

            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User)
                .WithMany(p => p.Orders)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Order_User");
        });

        modelBuilder.Entity<OrderItem>(entity =>
        {
            entity.HasKey(e => e.OrderItemId).HasName("PK__OrderIte__57ED06A13592DC4B");

            entity.Property(e => e.OrderItemId).HasColumnName("OrderItemID");

            entity.Property(e => e.EndDate).HasColumnType("datetime");

            entity.Property(e => e.OrderId).HasColumnName("OrderID");

            entity.Property(e => e.PriceAtPurchase)
                .HasColumnType("decimal(18, 2)");

            entity.Property(e => e.ProductId).HasColumnName("ProductID");

            entity.Property(e => e.StartDate).HasColumnType("datetime");

            entity.HasOne(d => d.Order)
                .WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK_Item_Order");

            entity.HasOne(d => d.Product)
                .WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Item_Product");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.ProductId).HasName("PK__Products__B40CC6EDB3A6032E");

            entity.Property(e => e.ProductId).HasColumnName("ProductID");

            entity.Property(e => e.Beds).HasDefaultValue(0);

            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");

            entity.Property(e => e.City).HasMaxLength(100);

            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.Property(e => e.IsAvailable).HasDefaultValue(true);

            entity.Property(e => e.OwnerId).HasColumnName("OwnerID");

            entity.Property(e => e.Price)
                .HasColumnType("decimal(18, 2)");

            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);

            entity.Property(e => e.TransactionType)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Sale");

            // הוספת שדות נוספים כמו Rooms
            entity.Property(e => e.Rooms).HasColumnType("int").IsRequired(false);
            entity.Property(e => e.Beds).HasColumnType("int").HasDefaultValue(0);

            entity.HasOne(d => d.Category)
                .WithMany(p => p.Products)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK_Product_Category");

            entity.HasOne(d => d.Owner)
                .WithMany(p => p.Products)
                .HasForeignKey(d => d.OwnerId)
                .HasConstraintName("FK_Product_Owner");
        });

        modelBuilder.Entity<ProductImage>(entity =>
        {
            entity.HasKey(e => e.ImageId).HasName("PK__ProductI__7516F4EC06356133");

            entity.Property(e => e.ImageId).HasColumnName("ImageID");

            entity.Property(e => e.AdditionalImageUrl).IsRequired();

            entity.Property(e => e.ProductId).HasColumnName("ProductID");

            entity.HasOne(d => d.Product)
                .WithMany(p => p.ProductImages)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_ProductImages_Products");
        });

        modelBuilder.Entity<PropertyInquiry>(entity =>
        {
            entity.HasKey(e => e.InquiryId).HasName("PK__Property__5D5E0C04");

            entity.Property(e => e.InquiryId).HasColumnName("InquiryID");

            entity.Property(e => e.ProductId).HasColumnName("ProductID");

            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.Property(e => e.OwnerId).HasColumnName("OwnerID");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(20);

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("New");

            entity.HasOne(d => d.Product)
                .WithMany()
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PropertyInquiry_Product");

            entity.HasOne(d => d.User)
                .WithMany()
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PropertyInquiry_User");

            entity.HasOne(d => d.Owner)
                .WithMany()
                .HasForeignKey(d => d.OwnerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PropertyInquiry_Owner");
        });

        modelBuilder.Entity<AdminInquiry>(entity =>
        {
            entity.HasKey(e => e.InquiryId).HasName("PK__AdminInq__5D5E0C05");

            entity.Property(e => e.InquiryId).HasColumnName("InquiryID");

            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(20);

            entity.Property(e => e.Subject)
                .IsRequired()
                .HasMaxLength(200);

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("New");

            entity.HasOne(d => d.User)
                .WithMany()
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_AdminInquiry_User");
        });

        modelBuilder.Entity<Rating>(entity =>
        {
            entity.HasKey(e => e.RatingId).HasName("PK__Ratings__FCCDF87C9C59D520");

            entity.Property(e => e.Host).HasMaxLength(255);

            entity.Property(e => e.Method).HasMaxLength(50);

            entity.Property(e => e.Path).HasMaxLength(500);

            entity.Property(e => e.RecordDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.Property(e => e.Referer).HasMaxLength(500);

            entity.Property(e => e.UserAgent).HasMaxLength(1000);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CCACCD718B81");

            entity.HasIndex(e => e.Email)
                .IsUnique()
                .HasDatabaseName("UQ__Users__A9D105344F93E089");

            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(e => e.IsAdmin).HasDefaultValue(false);

            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255);

            entity.Property(e => e.Phone).HasMaxLength(20);

            // הוספת Address למשתמש
            entity.Property(e => e.Address).HasMaxLength(500).IsRequired(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
