// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class AdminInquiry
{
    public int InquiryId { get; set; }

    public int? UserId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Subject { get; set; }

    public string Message { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string Status { get; set; }

    public virtual User User { get; set; }
}
